### PR TITLE
Add support for filesystems (free space, inodes, etc)

### LINKED ISSUE #2: df stats
there is only information about volume group and not capacity filesystem :
# TYPE aix_disk_free gauge
aix_disk_free{disk="hdisk1",vgname="ngamsoft",machine_serial="21475DV",lpar="GAMAY",group_id="32772"} 49664
aix_disk_free{disk="hdisk0",vgname="rootvg",machine_serial="21475DV",lpar="GAMAY",group_id="32772"} 61824

Is it possible to add "df" information or other to follow capacity of space disk ?

Regards
Frederic

_Originally posted by @fredtriplefred in https://github.com/thorhs/node_exporter_aix/issues/1#issuecomment-735800692_

### PR DESCRIPTION
**Pull request by thorhs**
This change hopefully resolves #2.  It adds support for jfs2 disk space and inode info to be reported, compatable with node_exporter.

### CODE REVIEW

**Review by fredtriplefred — COMMENTED** [review]
Hi Thorhallur
I just noticed that last message i wrote you was never send as request was closed.
Is it possible to add also JFS filesystem and not only JFS2 because we have again old school filesystem like this :
         /dev/hd4         /                jfs    Sep 11 12:20 rw,log=/dev/hd8 
         /dev/hd2         /usr             jfs    Sep 11 12:20 rw,log=/dev/hd8 
         /dev/hd9var      /var             jfs    Sep 11 12:20 rw,log=/dev/hd8 
         /dev/hd3         /tmp             jfs    Sep 11 12:20 rw,log=/dev/hd8 
         /dev/hd1         /home            jfs    Sep 11 12:21 rw,log=/dev/hd8 
         /dev/hd10opt     /opt             jfs    Sep 11 12:21 rw,log=/dev/hd8 
Regards
Frederic

**Comment by thorhs** [comment]
Hi @fredtriplefred,

Thanks for your continued suggestions on improvements, please keep them coming!

I have released v1.11.0 with support for JFS.  I tested it by adding a jfs filesystem to the build host and got data for it, but that was about the extent of testing.  It 'shold just work', but please let me know if it doesn't, since I don't have any jfs filesystems in use.

Also, it would be great if you could open up a new issue for every issue/question, it makes it easier to track both for me and others.

Thanks again,

Thor

**Comment by fredtriplefred** [comment]
Hi Thors
Thanks it works but is it normal that you leave fstype be fixed with jfs2 instead of jfs :
node_filesystem_size_bytes{device="/dev/hd4",fstype="jfs2",mountpoint="/",machine_serial="785A0A0",lpar="Merlot",cpupool_id="0",group_id="32771"} 11542724608
merlot.root.p560Q /tmp => mount
  node       mounted        mounted over    vfs       date        options      
-------- ---------------  ---------------  ------ ------------ --------------- 
         /dev/hd4         /                jfs    Sep 13 16:46 rw,log=/dev/hd8 

Not a problem but could be misleading in Grafana for example.

Regards
Frederic

**Comment by thorhs** [comment]
@fredtriplefred I have fixed that in v1.11.1, which is out now.

It was hardcoded to jfs2 since that is the only one I was looking for initially.

Thanks again for finding all these issues :)

**Pull request merged**
